#include "caf-pack/HeaderGenerator.hpp"
#include <fstream>
#include <algorithm>
#include <sstream>
#include <cctype>
#include <iomanip>

namespace CafPack {

uint64_t HeaderGenerator::fnv1aHash(const std::string& str) {
    uint64_t hash = 14695981039346656037ULL;
    for (char c : str) {
        hash ^= static_cast<unsigned char>(c);
        hash *= 1099511628211ULL;
    }
    return hash;
}

std::string HeaderGenerator::assetNameToIdentifier(const std::string& filename) {
    std::string id = filename;
    
    size_t dotPos = id.rfind('.');
    if (dotPos != std::string::npos) {
        id = id.substr(0, dotPos);
    }
    
    std::transform(id.begin(), id.end(), id.begin(), 
        [](unsigned char c) {
            if (!std::isalnum(c)) return '_';
            return std::tolower(c);
        }
    );
    
    if (!id.empty() && std::isdigit(id[0])) {
        id = "ASSET_" + id;
    }
    
    return id;
}

void HeaderGenerator::generateHeader(
    const std::vector<AssetEntry>& assets,
    const std::filesystem::path& outputPath
) {
    std::ofstream header(outputPath);
    if (!header) {
        return;
    }
    
    header << "// Auto-generated by caf-pack\n";
    header << "#pragma once\n\n";
    header << "#include \"core/Types.hpp\"\n\n";
    header << "namespace Assets {\n\n";
    
    for (const auto& asset : assets) {
        std::string id = assetNameToIdentifier(asset.name);
        header << "constexpr u64 " << id << " = 0x" 
               << std::hex << std::setfill('0') << std::setw(16) 
               << asset.id << std::dec << "ULL;\n";
    }
    
    header << "\n}  // namespace Assets\n";
    header.close();
}

}  // namespace CafPack
